// <auto-generated />
using System;
using DaysOff.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaysOff.Data.Migrations
{
    [DbContext(typeof(DaysOffDbContext))]
    [Migration("20260118145330_InitialAuthAndSchedule")]
    partial class InitialAuthAndSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DaysOff.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DaysOff.Data.Entities.UserScheduleSelection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatoonDaysOff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RotatingOffStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserScheduleSelections");
                });

            modelBuilder.Entity("DaysOff.Data.Entities.UserScheduleSelection", b =>
                {
                    b.HasOne("DaysOff.Data.Entities.AppUser", "User")
                        .WithOne("ScheduleSelection")
                        .HasForeignKey("DaysOff.Data.Entities.UserScheduleSelection", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaysOff.Data.Entities.AppUser", b =>
                {
                    b.Navigation("ScheduleSelection");
                });
#pragma warning restore 612, 618
        }
    }
}
